spring:
  application:
    name: TitleLibrary
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_PATH}
